---
- name: "Configuring Webserver using Docker"
  hosts: all
  tasks:

  - name: "Creating Directory"
    file:
      state: directory
      path: "/dvd"

  - name: "Mounting Directory"
    mount:
      src: "/dev/cdrom"
      path: "/dvd" 
      state: mounted
      fstype: "iso9660"

  - name: "DVD1"
    yum_repository:
      name: "dvd1"
      baseurl: "/dvd/AppStream"
      description: "AppStream"
      gpgcheck: no

  - name: "DVD2"
    yum_repository:
      name: "dvd2"
      baseurl: "/dvd/BaseOS"
      description: "BaseOS"
      gpgcheck: no

  - name: "Docker Repository"
    yum_repository:
      name: "docker"
      description: "docker repo" 
      baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
      gpgcheck: no

  - name: "Installing Docker Package"
    package:
      name: "docker-ce-18.09.1-3.el7.x86_64" 
      state: present
  
  - name: "Starting Docker Service"
    service:
      name: "docker"
      state: started
      enabled: yes

  - name: "Installing Docker SDK for Python3"
    command: "pip3 install docker"

  - name: "Copying Folder and HTML File"
    copy:
      src: "index.html"
      dest: "/var/www/html/"

  - name: "Creating Container using HTTPD Image"
    docker_container: 
      name: "Mywebserver"
      image: "httpd"
      state: started
      exposed_ports: "80"
      ports: "8080:80"
      volumes: /var/www/html/:/usr/local/apache2/htdocs/

  - firewalld:
      port: 80/tcp
      immediate: yes
      state: enabled
      permanent: true 